openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c-ccg/vc-api
paths:
components:
  schemas:
    UpdateCredentialStatus:
      type: object
      required: ['type', 'statusPurpose']
      description: Credential status information to be updated.
      additionalProperties: false
      properties:
        id: 
          type: string
        type: 
          type: string
        statusPurpose:
          type: string
        statusListIndex:
          type: string
        statusListCredential:
          type: string
      example:
        {
          "credentialStatus": [{ "type": "BitstringStatusList", "statusPurpose": "revocation" }]
        }
